
import java.util.Vector;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author L5C0T6
 */
public class Main_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Main_GUI
     */
    public Main_GUI() {
        initComponents();
    }
    
    Vector <Etel> rantottHus = new Vector<Etel>();    
    Vector <Etel> sultKrumpli = new Vector<Etel>();
    Vector <Etel> porkolt = new Vector<Etel>();
    
    
    Vector<Etel> osszesEladottEtel = new Vector<Etel>();
    
    void statisztika()
    {
        int osszeskoltott = 0;
        
        for(int i = 0; i < osszesEladottEtel.size();i++)
        {
            osszeskoltott += osszesEladottEtel.get(i).getAr();
        }
        if(osszeskoltott > 0)
            stat_bevetel.setText("" + osszeskoltott);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelabel0 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        etelKeszites = new javax.swing.JButton();
        adagokSzamaSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuAdagok = new javax.swing.JTextArea();
        etelValaszto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rendelesLeadas = new javax.swing.JButton();
        etelRendelesre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rendeltAdagokSzama = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stat_bevetel = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        rendeles_visszajelzo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namelabel0.setText("Etel felvitele:");

        nameLabel1.setText("Valasztek kilistazasa:");

        nameLabel2.setText("Rendeles:");

        etelKeszites.setText("Etelek elkeszitese");
        etelKeszites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etelKeszitesActionPerformed(evt);
            }
        });

        jLabel1.setText("Etel neve:");

        jLabel2.setText("Adagok szama:");

        menuAdagok.setColumns(20);
        menuAdagok.setRows(5);
        jScrollPane1.setViewportView(menuAdagok);

        etelValaszto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rantott hus", "Sult krumpli", "Porkolt" }));

        jLabel3.setText("Valasszon etelt:");

        rendelesLeadas.setText("Rendelés leadása");
        rendelesLeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendelesLeadasActionPerformed(evt);
            }
        });

        etelRendelesre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rantott hus", "Sult krumpli", "Porkolt" }));
        etelRendelesre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                etelRendelesreItemStateChanged(evt);
            }
        });

        jLabel4.setText("Adagok szama: ");

        jLabel5.setText("Statisztika");

        jLabel6.setText("Összes bevetel eddig: ");

        price.setText("Ára:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etelValaszto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adagokSzamaSpinner)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(etelKeszites)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rendelesLeadas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etelRendelesre, 0, 116, Short.MAX_VALUE)
                                .addComponent(rendeltAdagokSzama)))))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(namelabel0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel2)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(stat_bevetel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rendeles_visszajelzo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel0)
                    .addComponent(nameLabel1)
                    .addComponent(nameLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(etelValaszto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(adagokSzamaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(43, 43, 43)
                            .addComponent(etelKeszites))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(etelRendelesre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rendeltAdagokSzama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rendelesLeadas)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(stat_bevetel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rendeles_visszajelzo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etelKeszitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etelKeszitesActionPerformed
              
        for(int i = 0; i < (Integer)adagokSzamaSpinner.getValue(); i++)
        {
            if(etelValaszto.getSelectedItem().equals("Rantott hus"))
            {
                Etel tmp = new Etel((String)etelValaszto.getSelectedItem());
                rantottHus.add(tmp);
            }
            else if(etelValaszto.getSelectedItem().equals("Sult krumpli"))
            {
                Etel tmp = new Etel((String)etelValaszto.getSelectedItem());
                sultKrumpli.add(tmp);
            }
            else if(etelValaszto.getSelectedItem().equals("Porkolt"))
            {
                Etel tmp = new Etel((String)etelValaszto.getSelectedItem());
                porkolt.add(tmp);
            }      
        }
        listaz();
    }//GEN-LAST:event_etelKeszitesActionPerformed

    private void rendelesLeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendelesLeadasActionPerformed
      
        elemTorol((String)etelRendelesre.getSelectedItem(),(Integer)rendeltAdagokSzama.getValue());
        listaz();
        
        
    }//GEN-LAST:event_rendelesLeadasActionPerformed

    private void etelRendelesreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_etelRendelesreItemStateChanged
        
        if(etelRendelesre.getSelectedItem().equals("Rantott hus"))
        {
            if(rantottHus.size() > 0)
                price.setText("Ára: " + rantottHus.get(0).getAr());
            else
                price.setText("Jelenleg nem elérhető :(");
        }
        
        else if(etelRendelesre.getSelectedItem().equals("Sult krumpli"))
        {
            if(sultKrumpli.size() > 0)
                price.setText("Ára: " + sultKrumpli.get(0).getAr());
            else
                price.setText("Jelenleg nem elérhető :(");
        }
        
        else if(etelRendelesre.getSelectedItem().equals("Porkolt"))
        {
            if(porkolt.size() > 0)
                price.setText("Ára: " + porkolt.get(0).getAr());
            else
                price.setText("Jelenleg nem elérhető :(");
        }
        
            
    }//GEN-LAST:event_etelRendelesreItemStateChanged

    void elemTorol(String etelNeve, int mennyi)
    {
        int db = 0;
              if(etelNeve.equals("Rantott hus")  && rantottHus.size() > mennyi)
                {
                    for(int i = 0; i < mennyi ; i++)
                    {
                        osszesEladottEtel.add(rantottHus.lastElement());
                        rantottHus.remove(rantottHus.size()-1); 
                        db++;
                    }
                    ertesites(etelNeve,db);
                }
                else if(etelNeve.equals("Sult krumpli") && sultKrumpli.size() >= mennyi)
                {
                    for(int i = 0; i < mennyi ; i++)
                    {
                        osszesEladottEtel.add(sultKrumpli.lastElement());
                        sultKrumpli.remove(sultKrumpli.size()-1);  
                        db++;
                    }
                    ertesites(etelNeve,db);
                }
                else if(etelNeve.equals("Porkolt") && porkolt.size() > mennyi)
                {
                    
                    for(int i = 0; i < mennyi ; i++)
                    {
                        osszesEladottEtel.add(porkolt.lastElement());
                        porkolt.remove(porkolt.size()-1);
                        db++;
                    }
                    ertesites(etelNeve,db);
                }
                else
                {
                    ertesites("..",db);
                }
        } 
    
    
    void ertesites(String nev, int db)
    {
        if(db > 0)
            rendeles_visszajelzo.setText("Vásárolt " + db + " db " + nev + "t");
        else
            rendeles_visszajelzo.setText("Nincs ennyi a készleten");
    }
    
    private void listaz()
    {
        menuAdagok.setText("");
        if(rantottHus.size() > 0)        
            menuAdagok.append("Rantott hus: " + rantottHus.size() + "\n");
        
        if(sultKrumpli.size() > 0)
            menuAdagok.append("Sult krumpli: " + sultKrumpli.size() + "\n");
        
        if(porkolt.size() > 0)
            menuAdagok.append("Porkolt: " + porkolt.size());
        
        statisztika();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner adagokSzamaSpinner;
    private javax.swing.JButton etelKeszites;
    private javax.swing.JComboBox<String> etelRendelesre;
    private javax.swing.JComboBox<String> etelValaszto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea menuAdagok;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel namelabel0;
    private javax.swing.JLabel price;
    private javax.swing.JButton rendelesLeadas;
    private javax.swing.JLabel rendeles_visszajelzo;
    private javax.swing.JSpinner rendeltAdagokSzama;
    private javax.swing.JLabel stat_bevetel;
    // End of variables declaration//GEN-END:variables

}
